version: "3.8"
services:
  backend:
    image: "crdl93/springboot-react-fullstack:14.10.2021.0.48.15"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev